# Generated by Django 2.0.7 on 2018-07-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
